<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Welcome to <?php echo $this->siteName ?></title>
</head>
<body>
    <p>Dear <?php echo $this->name ?>,</p>
    <p>
        Thank you for signing up at <?php echo $this->siteName ?>.
        We welcome you to our service and here are the details:
    </p>

    <p>Site: http://<?php echo $this->url ?> </p>
    <p>Username: <?php echo $this->username ?> </p>
    <p>Password: ********** (hidden for security)</p>

    <p>Thanks</p>
    <p><?php echo $this->siteName ?> Support.</p>
</body>
</html>