
        <div class="modal-header">
            <a href="#" class="close" id="close-form">x</a>
            <h3>Add Category</h3>
        </div>

        <div class="modal-body">

            <form action="" method="POST" class="form-stacked">

                <fieldset>

                    <div class="clearfix">
                        <label for="xlInput">Title</label>

                        <div class="input">
                            <input class="large" id="xlInput" name="xlInput" size="30" type="text" value=""/>
                        </div>
                    </div>
                    <!-- /clearfix -->

                    <input type="submit" class="btn primary" value="Save changes"/>
                    <button type="reset" class="btn" id="#cancel-button">Cancel</button>

                </fieldset>
            </form>
        </div>