
    <h1>All Permission</h1>

    <div style="float:right">
<!--        <a class="btn success" data-controls-modal="role-modal" data-backdrop="static">Add Role</a>-->
    </div>

    <table id="draft-exams" class="zebra-striped" style="margin-top: 10px">

        <thead>
            <tr>
                <th width="40%"></th>
                <th width="20%">Super Admin</th>
                <th width="20%">Admin</th>
                <th width="20%">User</th>
            </tr>
        </thead>

        <tbody>

            <tr>
                <td>User Create</td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value="" checked="checked"/>
                     </label>
                </td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value="" checked="checked"/>
                     </label>
                </td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value=""/>
                     </label>
                </td>
            </tr>

            <tr>
                <td>User Edit</td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value="" checked="checked"/>
                     </label>
                </td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value="" checked="checked"/>
                     </label>
                </td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value=""/>
                     </label>
                </td>
            </tr>
            <tr>
                <td>User Delete</td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value="" checked="checked"/>
                     </label>
                </td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value="" checked="checked"/>
                     </label>
                </td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value=""/>
                     </label>
                </td>
            </tr>
            <tr>
                <td>User Management</td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value="" checked="checked"/>
                     </label>
                </td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value=""/>
                     </label>
                </td>
                <td>
                    <label class="add-on active">
                        <input type="checkbox" name="" id="" value=""/>
                     </label>
                </td>
            </tr>

        </tbody>

    </table>

    <div >
        <button type="submit" class="btn primary">Save</button>&nbsp;
    </div>

