
<div class="modal-header">
  <a href="#" class="close" id="close-form">x</a>
  <h3>New Role</h3>
</div>

<div class="modal-body">
    <form class="form-stacked" method="POST" action="">
        <fieldset>

            <div class="clearfix">
                <label for="title">Title</label>
                <div class="input">
                    <input type="text" class="span5" id="title" name="title" />
                </div>
            </div><!-- /clearfix -->

            <div class="clearfix">
                <label for="description">Description</label>
                <div class="input">
                    <textarea class="span5" id="description" name="description">
                    </textarea>

                </div>
            </div><!-- /clearfix -->
        </fieldset>

        <div>
            <button type="submit" class="btn primary">Save</button>&nbsp;
            <button type="reset" class="btn" id="cancel-button">Cancel</button>
        </div>
    </form>
</div>
