<div class="box box-100">
    <div class="boxin">
        <div class="content">
            <div style="padding: 10px; height: 300px; display: block; float: left; width: 50%;">
                <h2>You may <a href="javascript:back()">Go Back</a> or choose any of this pages</h2>
                <p style="font-size: 20px; color: #ff0000; padding-left: 10px;">
                    <?php echo $this->escape($this->message); ?>
                </p>

                <p style="padding-left: 10px;"><br /><br /><br />
                    <a href="mailto:<?php echo $this->siteEmail ?>" style="font-style: italic;">Click here</a>
                    to inform Graphic Magix about this error.
                </p>
            </div>
            <img align="right" alt="No Access" src="/images/No-Access.gif" style="margin: 5px" />

            <div class="clear"> &nbsp; </div>
        </div>
    </div>
</div>