    <h1>CSE 110 Online Exam</h1>

    <div class="span10 offset4">
        <div style="float: left; "><span style="font-weight: bold" >Questions</span>: 1 of 30</div>
        <div style="float: right;"><span style="font-weight: bold" >Time</span>: 13 of 30 </div>
        <hr/>
    </div>

    <div class='row'></div> <!--both clear-->
    <div class = "offset4">
        <P>
            <h4>
                What is the Capital of Bangladesh?
            </h4>

            <h6>
                <span style="font-style: italic;">Hints: Capital is the main city of a Country?</span>
            </h6>

            <ul class = "unstyled">
                <li><input type="checkbox" name="" id="" value=""/> <span style="padding-left: 5px">A. Chittagong</span></li>
                <li><input type="checkbox" name="" id="" value=""/> <span style="padding-left: 5px">B. Dhaka</span></li>
                <li><input type="checkbox" name="" id="" value=""/> <span style="padding-left: 5px">C. Bogra</span></li>
                <li><input type="checkbox" name="" id="" value=""/> <span style="padding-left: 5px">D. Rajshahi</span></li>
            </ul>
        </p>

    </div>

    <div class='offset4'>
         <button type="submit" class="btn primary" onclick="window.location='/exam/online-exams/next-exam'">Next</button>
    </div>





