<h1>CSE 110 Online Exam</h1>

<div class="span10 offset4">
    <div style="float: left; "><span style="font-weight: bold" >Questions</span>: 1 of 30</div>
    <div style="float: right;"><span style="font-weight: bold" >Time</span>: 13 of 30 </div>
    <hr/>
</div>

<div class='row'></div> <!--both clear-->
<div class = "offset4">
    <P>
        <h4>
            Which one is True?
        </h4>

        <h6>
            <span style="font-style: italic;">Hints: Definition of marketing</span>
        </h6>

        <ul class = "unstyled">
            <li><input type="radio" name="answer" id="" value=""/> <span style="padding-left: 5px">A. The action or business of promoting and selling products or services.</span></li>
            <li><input type="radio" name="answer" id="" value=""/> <span style="padding-left: 5px">B. The action taken to expand your business, inside your industry</span></li>

        </ul>
    </p>

</div>

<div class='offset4'>
     <button type="submit" class="btn primary" onclick="window.location='/exam/online-exams/next-exam'">Next</button>
</div>





