<h1>CSE 110 Online Exam</h1>

<div class="span10 offset4">
        <div style="float: left; "><span style="font-weight: bold" >Questions</span>: 3 of 30</div>
        <div style="float: right;"><span style="font-weight: bold" >Time</span>: 12 of 30 </div>
        <hr/>
</div>

<div class='row'></div> <!--both clear-->
<div class = "offset4">
    <P>
        <h4>
            What is the capital of Bangladesh?
        </h4>

        <h6>
             <span style="font-style: italic;">Hints: Capital is the main city of a country?</span>
        </h6>

        <textarea class="xxlarge" name="textarea" id="textarea" rows="3" ></textarea>


    </p>

</div>

<div class='offset4'>
     <button type="submit" class="btn primary" onclick="window.location='/exam/online-exams/next1-exam'">Next</button>
</div>





