
        <div class="modal-header">
            <h3>New User</h3>
        </div>

        <div class="modal-body">
            <form class="form-stacked" method="POST" action="">
                <fieldset>
                    <div class="clearfix">
                        <label for="username">Username</label>
                        <div class="input">
                            <input type="text" class="span5" id="username" name="username" />
                        </div>
                    </div><!-- /clearfix -->

                    <div class="clearfix">
                        <label for="password">Password</label>
                        <div class="input">
                            <input type="password" class="span5" id="password" name="password" />
                        </div>
                    </div><!-- /clearfix -->

                    <div class="clearfix">
                        <label for="confirmed_password">Confirmed Password</label>
                        <div class="input">
                            <input type="password" class="span5" id="confirmed_password" name="confirmed_password" />
                        </div>
                    </div><!-- /clearfix -->
                </fieldset>
                <fieldset>
                    <div class="clearfix">
                        <label for="full_name">Full Name</label>
                        <div class="input">
                            <input class="span5" id="full_name" name="full_name" />
                        </div>
                    </div><!-- /clearfix -->

                    <div class="clearfix">
                        <label for="email">Email Address</label>
                        <div class="input">
                            <input type="text" class="span5" id="email" name="email" />
                        </div>
                    </div><!-- /clearfix -->

                    <div class="clearfix">
                        <label for="phone">Contact Number</label>
                        <div class="input">
                            <input type="text" class="span5" id="phone" name="phone" />
                        </div>
                    </div><!-- /clearfix -->

                    <div class="clearfix">
                        <label for="stackedSelect">Status</label>
                        <div class="input">
                            <select name="status_id" id="stackedSelect">
                                <option>- Select Status -</option>
                                <option>Active</option>
                                <option>Inactive</option>
                                <option>Ban</option>
                            </select>
                        </div>
                    </div><!-- /clearfix -->

                    <div class="clearfix">
                        <label for="stackedSelect">Roles</label>
                        <div class="input">
                            <select name="role_id" id="stackedSelect">
                                <option>- Select Role -</option>
                                <option>Super Admin</option>
                                <option>Admin</option>
                                <option>User</option>
                            </select>
                        </div>
                    </div><!-- /clearfix -->
                </fieldset>

                <div>
                    <button type="submit" class="btn primary">Save</button>&nbsp;
                    <button type="reset" class="btn" id="cancel-button" onclick="window.location='/user/users'">Cancel</button>
                </div>
            </form>
        </div>
