
    <h1 style="float:left">All Users</h1>

    <div style="float:right">
        <a class="btn success" href="/user/users/add">New User</a>
    </div>

    <table id="draft-exams" class="zebra-striped" style="margin-top: 20px">

        <thead>
            <tr>
                <th width="10%">Serial</th>
                <th>Full Name</th>
                <th width="10%">Username</th>
                <th width="20%">Email Address</th>
                <th width="15%">Last Modified</th>
                <th width="17%">&nbsp;</th>
            </tr>
        </thead>

        <tbody>

            <tr>
                <td class="centered">1</td>
                <td>Emran Hasan</td>
                <td class="centered">phpfour</td>
                <td class="centered">phpfour@gmail.com</td>
                <td class="centered">22nd Sept, 2011 3:42pm</td>
                <td class="centered">
                    <button class="btn">Profile</button>
                    <button class="btn">Edit</button>
                    <button class="btn danger">Delete</button>
                </td>
            </tr>

            <tr>
                <td class="centered">2</td>
                <td>Raju Mazumdar</td>
                <td class="centered">rajuniit</td>
                <td class="centered">rajuniit@gmail.com</td>
                <td class="centered">22nd Sept, 2011 3:42pm</td>
                <td class="centered">
                    <button class="btn">Profile</button>
                    <button class="btn">Edit</button>
                    <button class="btn danger">Delete</button>
                </td>
            </tr>

            <tr>
                <td class="centered">3</td>
                <td>Rahim Khan</td>
                <td class="centered">Rahim</td>
                <td class="centered">rahim@gmail.com</td>
                <td class="centered">22nd Sept, 2011 3:42pm</td>
                <td class="centered">
                    <button class="btn">Profile</button>
                    <button class="btn">Edit</button>
                    <button class="btn danger">Delete</button>
                </td>
            </tr>

        </tbody>

    </table>

    <div class="span8">
      <div class="pagination">
        <ul>
          <li class="prev disabled"><a href="#">&larr; Previous</a></li>
          <li class="active"><a href="#">1</a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">3</a></li>
          <li class="next"><a href="#">Next &rarr;</a></li>
        </ul>
      </div>
    </div>


    <div id="user-modal" class="modal hide fade"></div>

    <script type="text/javascript">
        $(function(){
            $.ajax({
                url: '/user/users/add',
                type: 'POST',
                success: function(data){
                    $('#user-modal').html(data);
                }
            });
        });
    </script>