<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
</head>

<body>

<div class="container-fluid" style="margin: 0 auto">

    <div class="span8 offset7" style="margin-top:100px">

        <div id="login-panel" class="hero-unit" style="background-color:#F5F5DA">

            <form action="/user/users/login" method="POST">
                <fieldset>
                    <legend>Welcome to Devnet Exam System</legend>

                    <div class="clearfix">
                        <label for="username">Username</label>

                        <div class="input">
                            <input type="text" class="span4" id="username" name="username"/>
                        </div>
                    </div>
                    <!-- /clearfix -->

                    <div class="clearfix">
                        <label for="password">Password</label>

                        <div class="input">
                            <input type="text" class="span4" id="password" name="password"/>
                        </div>
                    </div>
                    <!-- /clearfix -->

                    <div style="padding: 10px 0 0 125px">
                        <button type="submit" class="btn primary" style="margin-right: 10px">Login</button>
                        <a href="/user/users/forget">Forget Password</a>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

</div>
<!-- #content -->

</body>
</html>