<h1>
    <a href="/user/users/profile">Profile Details</a>
</h1>

<div>

    <form action="" method="POST" class="form-stacked">
        <fieldset>
            <legend></legend>

            <div class="clearfix">
                <label>Username</label>

                <div class="input">
                    <input class="xxlarge" name="xlInput" size="30" type="text" value="admin"/>
                </div>
            </div>
            <!-- /clearfix -->

            <div class="clearfix">
                <label>Full Name</label>

                <div class="input">
                    <input class="xxlarge" name="xlInput" size="30" type="text" value="Eftakhairul Islam"/>
                </div>
            </div>
            <!-- /clearfix -->

            <div class="clearfix">
                <label>Contact Number</label>

                <div class="input">
                    <input class="xxlarge" name="xlInput" size="30" type="text" value="01712793451"/>
                </div>
            </div>
            <!-- /clearfix -->

            <div class="clearfix">
                <label>Email Address</label>

                <div class="input">
                    <input class="xxlarge" name="xlInput" size="30" type="text"
                           value="eftakhairul@gmail.com"/>
                </div>
            </div>
            <!-- /clearfix -->

            <input type="submit" class="btn primary" value="Save changes"/>
            <button type="reset" class="btn">Cancel</button>

        </fieldset>
    </form>
</div>