<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8" http-equiv="Accept-Encoding">
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
</head>

<body>

<div class="container-fluid" style="margin: 0 auto">

    <div class="span10 offset6" style="margin-top:50px">

        <div class="hero-unit" style="background-color:#F5F5DA">

            <form action="" method="POST">
                <fieldset>
                    <legend>Sign Up</legend>

                    <div class="clearfix">
                        <label for="username">Username</label>

                        <div class="input">
                            <input type="text" class="span4" id="username" name="username"/>
                        </div>
                    </div>
                    <!-- /clearfix -->

                    <div class="clearfix">
                        <label for="password">Password</label>

                        <div class="input">
                            <input type="text" class="span4" id="password" name="password"/>
                        </div>
                    </div>
                    <!-- /clearfix -->

                    <div style="padding: 10px 0 0 150px">
                        <a href="/user/users/login" class="btn primary">Login</a> or
                        <a href="/user/users/forget" style="display:inline-block;">Forget Password</a>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

</div>
<!-- #content -->

</body>
</html>